services:
  - type: web
    name: smart-recruiter-backend
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart-recruiter-db
          property: connectionString

databases:
  - name: smart-recruiter-db
    plan: free
