"""Added submission_id to Feedback model

Revision ID: 20cffb0d9071
Revises: c897c568fbf2
Create Date: 2025-07-28 00:53:59.131060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20cffb0d9071'
down_revision = 'c897c568fbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'submissions', ['submission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'submission_id')
    # ### end Alembic commands ###
