"""empty message

Revision ID: 2955dc595b97
Revises: 4840be055266
Create Date: 2025-08-08 20:36:19.449505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2955dc595b97'
down_revision = '4840be055266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('questions', sa.Column('options', sa.JSON(), nullable=True))
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_column('questions', 'question_text')
    op.drop_column('questions', 'choices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('choices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'text')
    # ### end Alembic commands ###
