"""Add password_hash to User

Revision ID: 348a446e7fd3
Revises: f5a6bfb1a53b
Create Date: 2025-08-08 03:34:59.355982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348a446e7fd3'
down_revision = 'f5a6bfb1a53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
