"""empty message

Revision ID: 4840be055266
Revises: b248d4b10ece
Create Date: 2025-08-08 20:21:22.286522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4840be055266'
down_revision = 'b248d4b10ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feedback')
    op.add_column('results', sa.Column('candidate_id', sa.Integer(), nullable=False))
    op.add_column('results', sa.Column('assessment_id', sa.Integer(), nullable=False))
    op.add_column('results', sa.Column('score', sa.Float(), nullable=False))
    op.add_column('results', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'results', 'assessments', ['assessment_id'], ['id'])
    op.create_foreign_key(None, 'results', 'users', ['candidate_id'], ['id'])
    op.drop_column('results', 'percentage')
    op.drop_column('results', 'status')
    op.drop_column('results', 'total_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('total_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('percentage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'updated_at')
    op.drop_column('results', 'score')
    op.drop_column('results', 'assessment_id')
    op.drop_column('results', 'candidate_id')
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recruiter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], name='feedback_recruiter_id_fkey'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], name='feedback_response_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey')
    )
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
