"""empty message

Revision ID: 48bd9a90086c
Revises: 2955dc595b97
Create Date: 2025-08-08 21:31:28.879570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bd9a90086c'
down_revision = '2955dc595b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'password')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('profile_picture_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('company_name', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
