"""empty message

Revision ID: 53f2e6e9f826
Revises: 68dd963b583f
Create Date: 2025-08-08 19:33:04.589251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53f2e6e9f826'
down_revision = '68dd963b583f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('choices', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('correct_answer', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    op.drop_column('questions', 'points')
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'choices')
    # ### end Alembic commands ###
