"""empty message

Revision ID: 68dd963b583f
Revises: 348a446e7fd3
Create Date: 2025-08-08 19:09:24.117194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68dd963b583f'
down_revision = '348a446e7fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('recruiter_id', sa.Integer(), nullable=False))
    op.add_column('invitations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('invitations', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_constraint('invitations_user_id_fkey', 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'users', ['recruiter_id'], ['id'])
    op.drop_column('invitations', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key('invitations_user_id_fkey', 'invitations', 'users', ['user_id'], ['id'])
    op.alter_column('invitations', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('invitations', 'updated_at')
    op.drop_column('invitations', 'recruiter_id')
    # ### end Alembic commands ###
