"""empty message

Revision ID: b248d4b10ece
Revises: 53f2e6e9f826
Create Date: 2025-08-08 20:01:43.173314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b248d4b10ece'
down_revision = '53f2e6e9f826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('answer_text', sa.Text(), nullable=False))
    op.drop_column('responses', 'answer')
    op.drop_column('responses', 'feedback')
    op.drop_column('responses', 'score')
    op.add_column('submissions', sa.Column('candidate_id', sa.Integer(), nullable=False))
    op.add_column('submissions', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.drop_constraint('submissions_invitation_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_user_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'users', ['candidate_id'], ['id'])
    op.drop_column('submissions', 'code')
    op.drop_column('submissions', 'invitation_id')
    op.drop_column('submissions', 'created_at')
    op.drop_column('submissions', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('submissions', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('invitation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('code', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_user_id_fkey', 'submissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('submissions_invitation_id_fkey', 'submissions', 'invitations', ['invitation_id'], ['id'])
    op.drop_column('submissions', 'submitted_at')
    op.drop_column('submissions', 'candidate_id')
    op.add_column('responses', sa.Column('score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('responses', 'answer_text')
    # ### end Alembic commands ###
