"""added foreign key to response

Revision ID: c897c568fbf2
Revises: 995bd088ed88
Create Date: 2025-07-27 23:13:27.740292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c897c568fbf2'
down_revision = '995bd088ed88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('submission_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'responses', 'submissions', ['submission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_column('responses', 'submission_id')
    # ### end Alembic commands ###
